# Site settings | 网站设置
title: Devil in the details
SEOTitle: Ashmore's Blog | Ashmore
header-img: img/home-bg-he.png
email: 1069696543@qq.com
description: "Ashmore's Blog"
keyword: "Ashmore, Ashmore's blog, Machine Learning, Neural Network, Python"
url: "http://AshmoreLivy.github.io" # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/AshmoreLivy/AshmoreLivy.github.io.git" #code repository | 代码仓库


# Sidebar settings | 侧边栏设置
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Meet me behind the mall"
sidebar-avatar: /img/head.jpg      # 头像480*480

# SNS settings | 社交网络设置
github_username: AshmoreLivy




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
# 转换时排除某些文件夹或文件。被排除的文件或文件夹的路径是相对于网站源码目录的，源码目录以外不受影响。
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

Regeneration: true    # 允许文件修改时自动重新生成网站。





# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Gitalk
gitalk:
  enable: true    # 是否开启Gitalk评论
  clientID: b68a186378a1e5e938c3                            #生成的clientID
  clientSecret: 5a9e564ba49d3dcc9290d5915723f4f7cd130fea    #生成的clientSecret
  repo: https://github.com/AshmoreLivy/Ashmoretalk    #仓库名称
  owner: AshmoreLivy    # github用户名
  admin: AshmoreLivy
  distractionFreeMode: true # 是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: a51738353fd3983fe0b04207da667bb8


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "爽爽",
        href: "http://haoshuang.site/"
    }
]
